/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVCView;

import MVCController.ControllerAbominodo;

/**
 *
 * @author DELL
 */
public class ViewAbominodo2 extends javax.swing.JFrame {
    private ControllerAbominodo controller = new ControllerAbominodo();

    /**
     * Creates new form ViewAbominodo2
     */
    public ViewAbominodo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Opt1 = new javax.swing.JButton();
        Opt2 = new javax.swing.JButton();
        Opt3 = new javax.swing.JButton();
        Opt0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("===Main Menu===");

        Opt1.setText("Play");
        Opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt1ActionPerformed(evt);
            }
        });

        Opt2.setText("View High Scores");
        Opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt2ActionPerformed(evt);
            }
        });

        Opt3.setText("View Rules");
        Opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt3ActionPerformed(evt);
            }
        });

        Opt0.setText("Quit");
        Opt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(Opt2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(Opt3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Opt1)
                            .addComponent(Opt0))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(Opt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Opt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Opt3)
                .addGap(18, 18, 18)
                .addComponent(Opt0)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt1ActionPerformed
        try {
        controller.viewData();
    } catch (Exception er) {
    }
    }//GEN-LAST:event_Opt1ActionPerformed

    private void Opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt2ActionPerformed
        try {
        controller.viewData1();
    } catch (Exception er) {
    }
    }//GEN-LAST:event_Opt2ActionPerformed

    private void Opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt3ActionPerformed
        try {
        controller.viewData2();
    } catch (Exception er) {
    }
    }//GEN-LAST:event_Opt3ActionPerformed

    private void Opt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt0ActionPerformed
    this.dispose();
    ViewAbominodo v = new ViewAbominodo();
    v.setVisible(true);
    }//GEN-LAST:event_Opt0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAbominodo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAbominodo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAbominodo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAbominodo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAbominodo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Opt0;
    private javax.swing.JButton Opt1;
    private javax.swing.JButton Opt2;
    private javax.swing.JButton Opt3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
